const teamLogos = {
    atlanta_hawks: require("./atlanta_hawks.png"),
    boston_celtics: require("./boston_celtics.png"),
    brooklyn_nets : require("./brooklyn_nets.png"),
    charlotte_hortnets: require("./charlotte_hornets.png"),
    chicago_bulls: require("./chicago_bulls.png"),
    cleveland_cavaliers: require("./cleveland_cavaliers.png"),
    dallas_mavericks: require("./dallas_mavericks.png"),
    denver_nuggets: require("./denver_nuggets.png"),
    detroit_pistons: require("./detroit_pistons.png"),
    golden_state_warriors: require("./golden_state_warriors.png"),
    houston_rockets: require("./houston_rockets.png"),
    indiana_pacers: require("./indiana_pacers.png"),
    los_angles_clippers: require("./los_angles_clippers.png"),
    los_angles_lakers: require("./los_angles_lakers.png"),
    memphis_grizzlies: require("./memphis_grizzlies.png"),
    miami_heat: require("./miami_heat.png"),
    milwaukee_bucks: require("./milwaukee_bucks.png"),
    minnesota_timberwolves: require("./minnesota_timberwolves.png"),
    new_orleans_pelicans: require("./new_orleans_pelicans.png"),
    new_york_knicks: require("./new_york_knicks.png"),
    oklahoma_city_thunder: require("./oklahoma_city_thunder.png"),
    orlando_magic: require("./orlando_magic.png"),
    philadelphia_76ers: require("./philadelphia_76ers.png"),
    phoenix_suns: require("./phoenix_suns.png"),
    chicago_bulls: require("./portland_trailblazers.png"),
    sacramento_kings: require("./sacramento_kings.png"),
    san_antonio_spurs: require("./san_antonio_spurs.png"),
    toronto_raptors: require("./toronto_raptors.png"),
    utah_jazz: require("./utah_jazz.png"),
    washington_wizards: require("./washington_wizards.png"),
}
  export default teamLogos;